<?php

declare(strict_types=1);

namespace PheFr\Codegen\Signing;

/**
 * Stamps generated files with a digest of their own content, and checks it later.
 *
 * The header is a fixed number of lines and the digest covers everything after it — a
 * file cannot hash its own hash, so the header is excluded by position rather than by
 * pattern matching. One class owns that line count so no verifier can disagree about
 * where the body starts.
 *
 * The path is hashed alongside the body, so a generated file copied to another
 * location fails verification rather than quietly passing.
 *
 * Deliberately not a sidecar manifest. That gives up hash-based detection of files
 * added to or deleted from the generated tree, but `generate --check` regenerates and
 * diffs the whole tree, which catches both.
 */
final readonly class Signer
{
    /**
     * Lines occupied by the header, including the open tag and strict_types.
     *
     * Changing this invalidates every signature in existence, which is intended: the
     * header format is part of what is being verified.
     */
    public const HEADER_LINES = 14;

    private const ALGORITHM = 'sha256';

    public function sign(string $relativePath, string $body): string
    {
        return $this->header($relativePath, $this->digest($relativePath, $body)) . $body;
    }

    public function verify(string $relativePath, string $contents): SignatureStatus
    {
        $declared = $this->declaredDigest($contents);

        if (null === $declared) {
            return SignatureStatus::Unsigned;
        }

        $body = self::bodyOf($contents);

        return hash_equals($this->digest($relativePath, $body), $declared)
            ? SignatureStatus::Valid
            : SignatureStatus::Tampered;
    }

    /**
     * Everything the digest covers: the file from the first line after the header.
     */
    public static function bodyOf(string $contents): string
    {
        $lines = explode("\n", $contents);

        if (count($lines) <= self::HEADER_LINES) {
            return '';
        }

        return implode("\n", array_slice($lines, self::HEADER_LINES));
    }

    private function digest(string $relativePath, string $body): string
    {
        return self::ALGORITHM . ':' . hash(self::ALGORITHM, $relativePath . "\n" . $body);
    }

    private function declaredDigest(string $contents): ?string
    {
        $header = implode("\n", array_slice(explode("\n", $contents), 0, self::HEADER_LINES));

        if (1 !== preg_match('/^ \* digest: (\S+)$/m', $header, $matches)) {
            return null;
        }

        return $matches[1];
    }

    private function header(string $relativePath, string $digest): string
    {
        // The trailing newline puts a blank line between the header and the body, and
        // brings the header to exactly HEADER_LINES lines. SignerTest locks that down,
        // because an off-by-one here silently shifts what the digest covers.
        return <<<PHP
            <?php

            declare(strict_types=1);

            /*
             * GENERATED BY PheFr — DO NOT EDIT.
             *
             * Regenerate with `phefr generate`. This file is machine-owned: edits are
             * detected by the build and rejected.
             *
             * path:   {$relativePath}
             * digest: {$digest}
             */

            PHP . "\n";
    }
}
